apiVersion: v2
name: yourls
description: Your Own URL Shortener
type: application
version: 1.0.2
appVersion: 1.7.3
icon: https://yourls.org/images/yourls-logo.png
dependencies:
  - name: mariadb
    version: 5.x.x
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mariadb.enabled
    tags:
      - yourls-database
